### ISSUE TITLE
version.h: No such file or directory

### ISSUE THREAD

**Issue by 3xxx** [philpem/magick#1]
can you help me ?thanks a lot.

**Comment by philpem** [comment]
You need to provide more information: e.g. what platform you're building on.

In any case this is old unsupported code.

**Comment by philpem** [comment]
If you want a quick fix you could remove the `#include` for version.h and hard code `#define`s for the `VER_`... constants. They're only printed to the screen for convenience anyway, they don't affect how the code works.
